use_frameworks!

platform :ios, '10.0'

target 'YYSegmentViewController_Example' do
  pod 'YYSegmentViewController', :path => '../'

  target 'YYSegmentViewController_Tests' do
    inherit! :search_paths

    
  end
end
